[package]
name = "json-rpc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.10", features = ["lua51", "module", "async", "serialize"] }
tokio = "1.43.0"
actix-web = "4.9.0"
actix-ws = "0.3.0"
serde_json = "1.0.135"
serde = { version = "1.0.217", features = ["derive"] }
uuid = { version = "1.12.0", features = ["v4"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.release]
tag = true
push = false
